# -*- coding: utf-8 -*-
"""Projekt-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17macsk5hxkz9U6LP1boW5JW_-CQ5isWo
"""

import random

print("Zdravím vás!")
print("-" * 30)
print("Vygeneroval jsem pro vás náhodné čtyřmístné číslo.")
print("Pojďme si zahrát Bulls and Cows.")
print("-" * 30)

def unikatni_4_mistne_cislo():
    cislice = ""
    while len(cislice) < 4:
        nova = str(random.randint(0, 9))
        if len(cislice) == 0 and nova == "0":
            continue
        if nova not in cislice:
            cislice += nova
    return cislice

def bulls_and_cows(secret, guess):
    bulls = 0
    cows = 0
    for i in range(4):
        if guess[i] == secret[i]:
            bulls += 1
        elif guess[i] in secret:
            cows += 1
    return bulls, cows

gen_cislo = unikatni_4_mistne_cislo()

pocet_pokusu = 0

while True:
    pokus = input("Zadej 4-místné číslo: ")

    if len(pokus) != 4 or not pokus.isdigit() or len(set(pokus)) != 4 or pokus[0] == "0":
        print("Chyba: Zadej platné 4-místné číslo s unikátními ciframi a první číslice nesmí být 0.")
        print("-" * 30)
        continue

    pocet_pokusu += 1

    bulls, cows = bulls_and_cows(gen_cislo, pokus)
    print(f"Bulls: {bulls}, Cows: {cows}")
    print("-" * 30)

    if bulls == 4:
        print(f"Správně, uhodli jste číslo {gen_cislo} na {pocet_pokusu} pokusů.")
        break