# -*- coding: utf-8 -*-
"""Projekt-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1di1odzidOzOqWKRx953DJLxxdhJ4IhQN
"""

import random

print("Zdravím vás!")
print("-" * 30)
print("Vygeneroval jsem pro vás náhodné čtyřmístné číslo.")
print("Pojďme si zahrát Bulls and Cows.")
print("-" * 30)

def unikatni_4_mistne_cislo():
    prvni_cislice = random.randint(1, 9)
    druha_cislice = random.randint(0, 9)
    while druha_cislice == prvni_cislice:
        druha_cislice = random.randint(0, 9)

    treti_cislice = random.randint(0, 9)
    while treti_cislice == prvni_cislice or treti_cislice == druha_cislice:
        treti_cislice = random.randint(0, 9)

    ctvrta_cislice = random.randint(0, 9)
    while ctvrta_cislice == prvni_cislice or ctvrta_cislice == druha_cislice or ctvrta_cislice == treti_cislice:
        ctvrta_cislice = random.randint(0, 9)

    return int(f"{prvni_cislice}{druha_cislice}{treti_cislice}{ctvrta_cislice}")

def bulls_and_cows(secret, guess):
    secret_str = str(secret)
    bulls = sum(1 for i in range(4) if secret_str[i] == guess[i])
    cows = sum(1 for x in guess if x in secret_str) - bulls
    return bulls, cows

gen_cislo = unikatni_4_mistne_cislo()

pocet_pokusu = 0

while True:
    pokus = input("Zadej 4-místné číslo: ")

    if len(pokus) != 4 or not pokus.isdigit() or len(set(pokus)) != 4 or pokus[0] == "0":
        print("Chyba: Zadej platné 4-místné číslo s unikátními ciframi a první číslice nesmí být 0.")
        print("-" * 30)
        continue

    pocet_pokusu += 1

    bulls, cows = bulls_and_cows(gen_cislo, pokus)
    print(f"Bulls: {bulls}, Cows: {cows}")
    print("-" * 30)

    if bulls == 4:
        print(f"Správně, uhodli jste číslo {gen_cislo} na {pocet_pokusu} pokusů.")
        break